export const EError = {
    ROUTING_ERROR:1, //RUTA NO EXISTE
    DATABASE_ERROR:2,//ERROR EN LA BASE DE DATOS
    AUTH_ERROR:3, //ERROR DE AUTENTICACION
    INVALIDAD_PARAM:4, //ERROR DE PARAMETROS  REFERENTES A LA RUTA
    UNAUTHORIZED_ERROR:5, //ERROR DE AUTORIZACION
    PRODUCT_CREATION_ERROR: 6,//ERROR AL AGREGAR PRODUCTO
    CART_CREATION_ERROR: 7//ERROR AL CREAR CARRITO
}